mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^polls1/', include('polls1.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='strategy'),  
    url(r'^best_strategy/$', views.best_strategy, name='best_strategy'),
    url(r'^best_opt_strategy/$', views.best_opt_strategy, name='best_opt_strategy'),
    url(r'^top_stocks/$', views.top_stocks, name='top_stocks'),
    url(r'^stocks_profit_of_strategies/(?P<strategy>.+)/$', views.stocks_profit_of_strategies, name='stocks_profit_of_strategies'),
    url(r'^strategies_profit_of_stocks/(?P<stock>.+)/$', views.strategies_profit_of_stocks, name='strategies_profit_of_stocks')
]

polls1/urls.py
from django.conf.urls import url

from . import views
app_name = 'polls1'
urlpatterns = [
     url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
import datetime 	
from django.db import models
from django.utils import timezone

class StocksStrategy(models.Model):
    strategies = models.CharField(max_length = 200)
    scrip = models.CharField(max_length = 200)
    parameters = models.CharField(max_length = 1000, null=True)
    profit = models.FloatField(max_length = 200)
    average = models.FloatField(max_length= 200, null=True)
    winrate = models.FloatField(max_length=200, null=True)
    trade =models.FloatField(max_length=200, null=True)
    default_value = models.BooleanField(default=False)
    pf = models.FloatField(max_length=200, null=True)
    def __str__(self):
        return self.strategies
    

polls1/models.py
from django.db import models
from django.utils import timezone
import datetime

class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self):              # __unicode__ on Python 2
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):              # __unicode__ on Python 2
        return self.name

class Entry(models.Model):
    blog = models.ForeignKey(Blog)
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    pub_date = models.DateField()
    mod_date = models.DateField()
    authors = models.ManyToManyField(Author)
    n_comments = models.IntegerField()
    n_pingbacks = models.IntegerField()
    rating = models.IntegerField()

    def __str__(self):              # __unicode__ on Python 2
        return self.headline


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from .models import StocksStrategy
from django.db.models import Max
import exteme


def index(request):
    dictt = StocksStrategy.objects.filter(default_value = True).distinct('strategies')
    return render(request, 'polls/strategy.html', {'dictt':(dictt,{},'Please Select Strategy')})

def best_strategy(request):
    dictt = StocksStrategy.objects.filter(default_value = True).distinct('scrip')
    return render(request, 'polls/best_strategy.html',{'dictt':(dictt, {}, 'Please Select Stock')})

def best_opt_strategy(request):
    dictt = StocksStrategy.objects.raw('select * from (select distinct on (s.scrip) s.scrip, s.id, s.profit from polls_stocksstrategy s where s.default_value = False and profit in (select max(profit) from polls_stocksstrategy where default_value = False group by scrip)) sb order by sb.profit DESC')
    return render(request, 'polls/best_opt_strategy.html',{'dictt':dictt})

def top_stocks(request):
    dictt = StocksStrategy.objects.raw('select *, profit as max_profit from polls_stocksstrategy where profit in (select max(profit) from polls_stocksstrategy where default_value = True group by scrip) and default_value= True order by profit DESC')
    return render(request, 'polls/top_stocks.html',{'dictt':dictt})

def stocks_profit_of_strategies(request, strategy):
    dictt = StocksStrategy.objects.filter(default_value = True).distinct('strategies')
    scripts_profit = StocksStrategy.objects.filter(strategies=strategy, default_value = True).order_by('-profit')
    return render(request, 'polls/strategy.html',{'dictt' : (dictt, scripts_profit,strategy)})

def strategies_profit_of_stocks(request, stock):
    dictt = StocksStrategy.objects.filter(default_value = True).distinct('scrip')
    scripts_profit = StocksStrategy.objects.filter(scrip=stock, default_value = True).order_by('-profit')
    return render(request, 'polls/best_strategy.html',{'dictt' : (dictt, scripts_profit, stock)})

polls1/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'polls1/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls1/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls1/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls1/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls1:results', args=(question.id,)))

polls/templates/polls/best_opt_strategy.html
<script>
function myFunction(name) {
	ele = document.getElementById(name)
	if (ele.style.display == 'block'){
  		ele.style.display = 'none';}
	else{
		ele.style.display = 'block';
		}
}
</script>
{% load staticfiles %}

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">


<div class="mdl-layout mdl-js-layout">
    <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
            <span class="mdl-layout__title">Optimized Strategies</span>
            <div class="mdl-layout-spacer"></div>
            <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="/polls/">Strategies</a>
            <a class="mdl-navigation__link" href="/polls/best_strategy/">Stocks</a>
            <a class="mdl-navigation__link" href="/polls/top_stocks/">Top Stocks</a>
            <a class="mdl-navigation__link" href="/polls/best_opt_strategy/">Optimized Strategies</a>
      </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout__title">Optimized Strategies</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="/polls/">Strategies</a>
            <a class="mdl-navigation__link" href="/polls/best_strategy/">Stocks</a>
            <a class="mdl-navigation__link" href="/polls/top_stocks/">Top Stocks</a>
            <a class="mdl-navigation__link" href="/polls/best_opt_strategy/">Optimized Strategies</a>
        </nav>
     </div>
    <main class="mdl-layout__content">
           <div class="mdl-grid">
                       <div class="mdl-cell mdl-cell--2-col"></div>
                        <div class="mdl-cell mdl-cell--8-col">
                                    <table class="mdl-data-table mdl-js-data-table">
                                      <thead>
                                        <tr>
                                          <th class="mdl-data-table__cell--non-numeric">Script</th>
                                          <th class="mdl-data-table__cell--non-numeric">Strategy</th>
                                          <th class="mdl-data-table__cell--non-numeric">Profit</th>
                                          <th >Parameter</th>
                                        </tr>
                                      </thead>
                                {% for stocks in dictt %}
                                    <tr>
                                        <td class="mdl-data-table__cell--non-numeric">{{stocks.scrip}}</td>
                                        <td class="mdl-data-table__cell--non-numeric">{{stocks.strategies}}</td>
                                        <td class="mdl-data-table__cell--non-numeric">{{stocks.profit}}</td>
                                        <td>{{stocks.parameters}}</td>
                                    </tr>
                                {% endfor %}
                                </table>
                       </div>
               <div class="mdl-cell mdl-cell--2-col"></div>
           </div>
    </main>
</div>

polls/templates/polls/best_strategy.html
<script>
function myFunction(name) {
	ele = document.getElementById(name)
	if (ele.style.display == 'block'){
  		ele.style.display = 'none';}
	else{
		ele.style.display = 'block';		
		}
}
</script>
<style type="text/css">
  .left-arrow {
  display: inline-block;
  position: relative;
  background: lavender;
  padding: 15px;
}
.left-arrow:after {
  content: '';
  display: block;  
  position: absolute;
  right: 100%;
  top: 50%;
  margin-top: -10px;
  width: 0;
  height: 0;
  border-top: 10px solid transparent;
  border-right: 10px solid lavender;
  border-bottom: 10px solid transparent;
  border-left: 10px solid transparent;
}
</style>
{% load staticfiles %}



<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">


<div class="mdl-layout mdl-js-layout">
    <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
            <span class="mdl-layout__title">Stocks</span>
            <div class="mdl-layout-spacer"></div>
            <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="/polls/">Strategies</a>
            <a class="mdl-navigation__link" href="/polls/best_strategy/">Stocks</a>
            <a class="mdl-navigation__link" href="/polls/top_stocks/">Top Stocks</a>
            <a class="mdl-navigation__link" href="/polls/best_opt_strategy/">Optimized Strategies</a>
      </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout__title">Stocks</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="/polls/">Strategies</a>
            <a class="mdl-navigation__link" href="/polls/best_strategy/">Stocks</a>
            <a class="mdl-navigation__link" href="/polls/top_stocks/">Top Stocks</a>
            <a class="mdl-navigation__link" href="/polls/best_opt_strategy/">Optimized Strategies</a>
        </nav>
     </div>
      <main class="mdl-layout__content">
                    <div class="mdl-grid">
                       <div class="mdl-cell mdl-cell--2-col" style="background-color: lavender; height:85%;overflow-y: scroll; overflow-x: hidden;">
                               {% for scripts in dictt.0 %}
                                    <a class="mdl-button mdl-js-button mdl-button--primary" href="{% url 'strategies_profit_of_stocks' scripts.scrip %}" style="width:100%;text-align: left">
                                      {{ scripts.scrip }}
                                    </a>
                               {% endfor %}
                       </div>
                        <div class="mdl-cell mdl-cell--2-col">
                          <div class="left-arrow" style="width:85%"><b style="color:rgb(63,81,181);text-transform: uppercase;">{{ dictt.2 }}</b>
                        </div>
                        </div>
                       <div class="mdl-cell mdl-cell--8-col" style="height:85%; overflow-y:scroll;">
                                <table class="mdl-data-table mdl-js-data-table" style="width:50%">
                                  <thead>
                                    <tr>
                                      <th class="mdl-data-table__cell--non-numeric">Strategy</th>
                                      <th>Profit</th>
                                    </tr>
                                  </thead>
                                    {% for strategy_profit in dictt.1 %}
                                        <tr>
                                         <td class="mdl-data-table__cell--non-numeric">{{strategy_profit.strategies}}</td><td>{{strategy_profit.profit}}</td>
                                            </tr>
                                     {% endfor %}
                                </table>
                       </div>
                    </div>
      </main>
</div>

polls/templates/polls/detail.html
YOU ARE SHOWING <u> {{stgy_id}} </u> NUMBER STRATEGIES

polls/templates/polls/index.html
 <ul>
    {% for question in questions %}
    	<li><a href="/polls/{{ question.id }}/">{{ question.id }}{{ question.question_text }}{{ question.pub_date }}</a></li>
    {% endfor %}
 </ul>

polls/templates/polls/stocks_profit_of_strategies.html
{{stgy.1}}<br/>
{% for strategy in stgy.0 %}
{{strategy.script}}{{strategy.profit}}<br/>
{% endfor %}

polls/templates/polls/strategy.html
<script>
function myFunction(name) {
	ele = document.getElementById(name)
	if (ele.style.display == 'block'){
  		ele.style.display = 'none';}
	else{
		ele.style.display = 'block';		
		}
}
</script>
<style type="text/css">
  .left-arrow {
  display: inline-block;
  position: relative;
  background: lavender;
  padding: 15px;
}
.left-arrow:after {
  content: '';
  display: block;  
  position: absolute;
  right: 100%;
  top: 50%;
  margin-top: -10px;
  width: 0;
  height: 0;
  border-top: 10px solid transparent;
  border-right: 10px solid lavender;
  border-bottom: 10px solid transparent;
  border-left: 10px solid transparent;
}
</style>
{% load staticfiles %}

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="mdl-layout mdl-js-layout">
    <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
            <span class="mdl-layout__title">Strategies</span>
            <div class="mdl-layout-spacer"></div>
            <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="/polls/">Strategies</a>
            <a class="mdl-navigation__link" href="/polls/best_strategy/">Stocks</a>
            <a class="mdl-navigation__link" href="/polls/top_stocks/">Top Stocks</a>
            <a class="mdl-navigation__link" href="/polls/best_opt_strategy/">Optimized Strategies</a>

      </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout__title">Strategies</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{% url 'strategy'%}">Strategies</a>
            <a class="mdl-navigation__link" href="/polls/best_strategy/">Stocks</a>
            <a class="mdl-navigation__link" href="/polls/top_stocks/">Top Stocks</a>
            <a class="mdl-navigation__link" href="/polls/best_opt_strategy/">Optimized Strategies</a>
        </nav>
     </div>
      <main class="mdl-layout__content">
           <div class="mdl-grid">
                       <div class="mdl-cell mdl-cell--2-col" style="background-color: lavender; height:85%; overflow-y: scroll; overflow-x: hidden; position: fixed">
                               {% for strategy in dictt.0 %}
                                    <a class="mdl-button mdl-js-button mdl-button--primary" href="{% url 'stocks_profit_of_strategies' strategy %}" style="width:100%;text-align: left">
                                      {{ strategy }}
                                    </a>
                               {% endfor %}
                       </div>
                       <div class="mdl-cell mdl-cell--2-col"></div>
                        <div class="mdl-cell mdl-cell--2-col">
                        <div class="left-arrow" style="width:13% ;position:fixed"><b style="color:rgb(63,81,181);text-transform: uppercase;">{{dictt.2}}</b>
                        </div>
                         
                        </div>
                       <div class="mdl-cell mdl-cell--8-col" style="height:85%;">
                                  <table class="mdl-data-table mdl-js-data-table" style="width:50%">
                                  <thead>
                                    <tr>
                                      <th class="mdl-data-table__cell--non-numeric">Script</th>
                                      <th>Profit</th>
                                    </tr>
                                  </thead>                               
                                    {% for stock_profit in dictt.1%}
                                      <tr>
                                         <td class="mdl-data-table__cell--non-numeric">{{stock_profit.scrip}}</td><td>{{stock_profit.profit}}</td>
                                      </tr>
                                     {% endfor %}
                                </table>
                       </div>
            </div>

      </main>
</div>

polls/templates/polls/top_stocks.html
<script>
function myFunction(name) {
	ele = document.getElementById(name)
	if (ele.style.display == 'block'){
  		ele.style.display = 'none';}
	else{
		ele.style.display = 'block';
		}
}
</script>

{% load staticfiles %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="mdl-layout mdl-js-layout">
    <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
            <span class="mdl-layout__title">Top Stocks</span>
            <div class="mdl-layout-spacer"></div>
            <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="/polls/">Strategies</a>
            <a class="mdl-navigation__link" href="/polls/best_strategy/">Stocks</a>
            <a class="mdl-navigation__link" href="/polls/top_stocks/">Top Stocks</a>
            <a class="mdl-navigation__link" href="/polls/best_opt_strategy/">Optimized Strategies</a>

      </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout__title">Top Stocks</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="/polls/">Strategies</a>
            <a class="mdl-navigation__link" href="/polls/best_strategy/">Stocks</a>
            <a class="mdl-navigation__link" href="/polls/top_stocks/">Top Stocks</a>
            <a class="mdl-navigation__link" href="/polls/best_opt_strategy/">Optimized Strategies</a>
        </nav>
     </div>
      <main class="mdl-layout__content">
           <div class="mdl-grid">
               <div class="mdl-cell mdl-cell--3-col"></div>
               <div class="mdl-cell mdl-cell--6-col">
                <table class="mdl-data-table mdl-js-data-table" style="width:100%">
                  <thead>
                    <tr>
                      <th class="mdl-data-table__cell--non-numeric">Stock</th>
                      <th class="mdl-data-table__cell--non-numeric">Strategy</th>
                      <th>Profit</th>
                    </tr>
                  </thead>
                    {% for script in dictt %}
                        <tr>
                         <td class="mdl-data-table__cell--non-numeric">{{ script.scrip }}</td>
                         <td class="mdl-data-table__cell--non-numeric">{{ script.strategies}}</td>
                         <td >{{ script.max_profit }}</td>
                            </tr>
                    {% endfor %}
                     </table>
                   </div>
                  <div class="mdl-cell mdl-cell--3-col"></div>

            </div>

      </main>
</div>

polls/templates/polls/tst.html
<html lang="en">
  <head>
    
  </head>
  <body>
<div class="container">

  <!-- columns should be the immediate child of a .row -->
  <div class="row">
    <div class="one column">One</div>
    <div class="eleven columns">Eleven</div>
  </div>

  <!-- just use a number and class 'column' or 'columns' -->
  <div class="row">
    <div class="two columns">Two</div>
    <div class="ten columns">Ten</div>
  </div>

  <!-- there are a few shorthand columns widths as well -->
  <div class="row">
    <div class="one-third column">1/3</div>
    <div class="two-thirds column">2/3</div>
  </div>
  <div class="row">
    <div class="one-half column">1/2</div>
    <div class="one-half column">1/2</div>
  </div>

</div>
    
  </body>
</html>

polls1/templates/polls1/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls1:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" valuepolls1:="Vote" />
</form>

polls1/templates/polls1/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls1/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls1/templates/polls1/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls1:detail' question.id %}">Vote again?</a>